language: cpp
sudo: required

dist: bionic

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-9
            - g++-9


jobs:
  include:
      # Linux 64-bit
    - stage: build and test
      name: Linux 64-bit
      os: linux
      install: &install_linux
        - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
        - sudo unlink /usr/bin/g++ && sudo ln -s /usr/bin/g++-9 /usr/bin/g++
        - wget https://github.com/Kitware/CMake/releases/download/v3.15.0-rc3/cmake-3.15.0-rc3-Linux-x86_64.tar.gz
        - tar -xf cmake-3.15.0-rc3-Linux-x86_64.tar.gz
        - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.0-rc3-Linux-x86_64/bin/cmake /home/travis/bin/cmake
        - sudo ln -s ${TRAVIS_BUILD_DIR}/cmake-3.15.0-rc3-Linux-x86_64/bin/ctest /home/travis/bin/ctest
      env: &linux-64-toolchain
        - TOOLCHAIN=""
      script: &script_linux
        - mkdir build && cd build
        - cmake ${TOOLCHAIN} ..
	- cmake --build .

